openapi: 3.0.2
info:
  title: API de Gestion des Utilisateurs
  version: 1.0.0
  description: API de gestion des utilisateurs et des auteurs 
paths:
  /authors:
    get:
      summary: Récupérer la liste des auteurs
      description: Récupérez la liste complète des auteurs dans la base de données.
      responses:
        '200':
          description: Liste des auteurs récupérée avec succès
    put:
      summary: Mettre à jour un auteur par ID
      description: Mettez à jour les informations d'un auteur en fonction de son ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Author"
      responses:
        '200':
          description: Auteur mis à jour avec succès
    delete:
      summary: Supprimer un auteur par ID
      description: Supprimez un auteur en fonction de son ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Auteur supprimé avec succès
components:
  schemas:
    Students:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        birth_date:
          type: string
          format: date
    Author:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        sex:
          type: string
